### ISSUE TITLE
LICENSE needed

### ISSUE THREAD

**Issue by mgalland** [bioinformatics-core-shared-training/cruk-summer-school-2020#2]
Dear CRUK bioinformaticians, 
I love your teaching materials and would like to inquire whether it is possible to re-use (with citations) some of your slides and website content?
Would you be willing to add a license to your teaching materials to allow re-use?
Many thanks in advance
Marc

**Comment by mfernandes61** [comment]
Had to consult with CRUK & Non-CRUK partners but now released under CC-by licence :-)
